server:
  port: 50304

newrelic:
  appname: mumbai.qlistener.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

service:
  geoip_path: /home/centos/go/src/github.com/vostrok/qlistener/dev/GeoLite2-City.mmdb
  threads_count: 1
  subscriptions_load_days: 5

  consumer:
    uri: amqp://linkit:dg-U_oHhy7-@52.66.23.201:5672
    queue_prefetch_count: 4
    binding_key: ""
    reconnect_delay: 10

  queues:
    access_campaign: access_campaign
    content_sent: content_sent

  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_dev
    user: linkit
    pass: E0kZN8pUAs63wePepf
    port: 5432
    host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
    ssl_mode: disable
    table_prefix: xmp_

  tables:
  - subscriptions
  - campaigns
