server: #linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
  port: 50304

service:
  geoip_path: /home/centos/go/src/github.com/vostrok/qlistener/dev/GeoLite2-City.mmdb
  threads_count: 1
  subscriptions_load_days: 5
  tables:
  - campaigns

consumer:
  conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: ec2-35-154-8-158.ap-south-1.compute.amazonaws.com
      port: 5672
  queue_prefetch_count: 4
  binding_key: ""
  reconnect_delay: 10

queues:
  access_campaign: access_campaign
  content_sent: content_sent
  user_actions: user_actions

db:
  conn_ttl: -1
  max_conns: 15
  timeout: 30
  name: linkit_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: ec2-35-154-8-158.ap-south-1.compute.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

