server:
  port: 70501

newrelic:
  appname: qlistener.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

service:
  geoip_path: dev/GeoIp/GeoLite2-City.mmdb
  rbmq_url: amqp://linkit:dg-U_oHhy7-@52.66.23.201:5672
  table_prefix: xmp_
  tables:
  - subscriptions
  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_dev
    user: linkit
    pass: E0kZN8pUAs63wePepf
    port: 5432
    host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
    table_prefix: xmp_