server:
  port: 70501

newrelic:
  appname: qlistener.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

service:
  rbmq_url: http://RBMQ.Url
  table_prefix: xmp_
  tables:
  - subscriptions
  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name:
    user:
    pass:
    port:
    host:
    table_prefix: xmp_